using System.Text;
using Microsoft.CodeAnalysis;

namespace FlowNet.SourceGenerators.Shared;

internal static class CommonCodeExtensions
{
    extension(StringBuilder sb)
    {
        public void AppendTypeHeader(out int indent, INamedTypeSymbol type, bool fileLevelNamespace = true)
        {
            indent = type.GenerateTypeHeader(sb, fileLevelNamespace);
        }

        public void AppendCommonHeader()
        {
            sb.AppendLine("// The file was generated by Flow.NET source generators, do NOT edit it manually.");
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using FlowNet.Core;");
            sb.AppendLine("using FlowNet.ComponentModel;");
        }
    }
}
